Feature/mbx #2057 Fix inapps overlapping
mindbox-cloud/android-sdk pull request #313
Opened 2023-03-16 11:25 UTC by enotniy

2023-03-16 11:59 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayerImpl.kt
> +                    isInAppMessageActive = true
Так нельзя делать, мы не должны считать инапп показаным, если он не показался. Если картинка, например, не загрузилась, и поэтому мы не увидели инапп, то мы не должны считать его показанным

2023-03-16 12:00 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManagerImpl.kt
> +                        if (isInAppShown()) {
Если эту штуку менять, то мб ее прям в интерактор вынести, чтобы мы не проверяли даже таргетинг

2023-03-16 12:00 UTC, Robalim requested changes
Нельзя менять флаг

2023-03-16 12:34 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayerImpl.kt
> +                    isInAppMessageActive = true
Так этот флаг и не отвечает за показ, а за активность. Как я понял он убирается, когда инап скрывается. Проблема в том, что иннап показывается асинхронно и второй успевает показаться до флага. Думаешь надо саспендить?

2023-03-16 12:52 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayerImpl.kt
> +                    isInAppMessageActive = true
Да, ты прав. Сергей говорит, что такой кейс в бэклоге есть. Уточню, будем ли мы чинить в текущем тикете

2023-03-17 08:30 UTC, Robalim approved these changes
Возможно стоит проставить флаг в false при ошибке

2023-03-17 09:33 UTC, merged