Feature/mbx 2456
mindbox-cloud/android-sdk pull request #337
Opened 2023-04-24 12:39 UTC by Robalim

https://github.com/orgs/mindbox-cloud/projects/69?pane=issue&itemId=24866425

2023-04-24 14:12 UTC, enotniy requested changes

2023-04-24 14:12 UTC, enotniy commented on dependencies.gradle
> +        coil: 'io.coil-kt:coil:2.3.0'
тогда отлюда убрать надо, если не затаскиваем

2023-04-24 14:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppChoosingManagerImpl.kt
> +            if (!isInAppContentFetched) continue
тут надо логи написать, почему скипаем

2023-04-24 14:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/di/Modules.kt
> +                OkHttpClient.Builder().connectTimeout(3, TimeUnit.SECONDS).build()
мы договаривались что это время можно переорпеделить. Самый простой положить в ресурсы

2023-04-24 14:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppChoosingManagerImpl.kt
> +                withContext(Job() + Dispatchers.IO) {
кажется два вызов async + awaitAll выглядело бы лучше

2023-04-24 16:02 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppChoosingManagerImpl.kt
> +                withContext(Job() + Dispatchers.IO) {
ты же все равно их запускаешь параллельно из-за Dispatchers.IO. Так это будет написано явно

2023-04-24 16:42 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppChoosingManagerImpl.kt
> +                withContext(Job() + Dispatchers.IO) {
Все равно не понял. Если ты имеешь в виду просто заменить launch на async, то я не понимаю в чем разнциа. А если ты хочешь просто async, без withContext(), то я не хочу дергать globalScope, это выглядит как очень рискованная идея

2023-04-25 07:26 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppChoosingManagerImpl.kt
> +                withContext(Job() + Dispatchers.IO) {
Я понял, я ошибся. Думал, что тут уже запускается в какой-то корутине

Тогда просто 
`listOf(
launch {}, 
launch {}).joinAll()`

Заменить на 

`joinAll(
launch {}, 
launch {})`

2023-04-25 08:17 UTC, merged