MBX-2529: Add parsing and validation models for abtests
mindbox-cloud/android-sdk pull request #357
Opened 2023-06-07 16:36 UTC by enotniy

Добавил валидаторы блока abtests и тесты для них

2023-06-09 08:36 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
>      private var operations: Map<OperationName, OperationSystemName>? = null
Возможно стоит вынести в мобильный бэклог, перенос этих штук в sessionManager, выглядит, что в будущем это будет правильнее

2023-06-09 08:36 UTC, Robalim approved these changes

2023-06-09 09:33 UTC, dbvasilyev requested changes
Договорились оторвать отсюда mixerFixedHash, и учесть те же замечания про логирования что и в предыдущем ПР-е.

2023-06-09 12:47 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
>      private var operations: Map<OperationName, OperationSystemName>? = null
Добавил тикет на исправление. Из-за этих штук тригерится парсинг несколько раз

2023-06-09 12:55 UTC, enotniy commented
> Договорились оторвать отсюда mixerFixedHash, и учесть те же замечания про логирования что и в предыдущем ПР-е.

Про mixerFixedHash - убираю как и договорились.
Про логирование - можно поподробнее, на чем мы остановились? 

- Уровень логирования не тот?
- Все логи с заглавной буквы?
- Расписывать подробнее с контекстом?

2023-06-13 08:18 UTC, dbvasilyev commented
> Про логирование - можно поподробнее, на чем мы остановились?

Ровно на том что записано в аспекте https://www.notion.so/mindbox/SDK-71d53a778b9643a8a0fe0373f48061fd и на здравом смысле. Если в аспекте чего-то не хватает, надо дописывать.

2023-06-13 08:24 UTC, dbvasilyev commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapper.kt
> +                        maxVersion = dto.sdkVersion?.maxVersion,
Не уверен что тут правильно. Точно должен быть "?" ? Ведь `sdkVersion` всегда должен быть и `minVersion` у него тоже.

2023-06-13 08:25 UTC, dbvasilyev commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
> +            mindboxLogE("Error parse abtests", e)
Это Warning. Давай поправим?

2023-06-13 08:26 UTC, dbvasilyev commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
> +            mindboxLogE("Error parse abtests", e)
Не, я не прав, Error тут валиден.

2023-06-13 08:42 UTC, dbvasilyev approved these changes

2023-06-13 09:03 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapper.kt
> +                        maxVersion = dto.sdkVersion?.maxVersion,
Объект sdkVersion переиспользован из inapps блока. Менять обе логики в рамках этого тикета не хорошо. Можно только воспользоваться !! (assert), но лучше это будет проверено на уровне валидатора, чем здесь кинет exception здесь

2023-06-13 09:04 UTC, merged