#MBX-2529 Add abtests logic
mindbox-cloud/android-sdk pull request #358
Opened 2023-06-07 16:54 UTC by enotniy

Добавил основную логику abtets и тесты для нее

2023-06-09 08:08 UTC, dbvasilyev requested changes

2023-06-09 08:08 UTC, dbvasilyev commented on sdk/src/test/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogicTest.kt
> +    fun `abtest logic two variants with inapps1`() = runTest {
Не понятно что в тестах в названиях обозначает "with inapps1" "with inapps2"
Давай всем этим тестам дадим названия которые будут описывать какие продуктовые кейсы они проверяют.

Из-за этого к сожалению не могу поревьювить тесты тут.

2023-06-09 10:57 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogic.kt
> +            this@InAppABTestLogic.mindboxLogW("Config inApps is empty. Skip logic.")
тут бесполезный лог по факту

2023-06-09 11:03 UTC, dbvasilyev commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogic.kt
> +            this@InAppABTestLogic.mindboxLogW("Config inApps is empty. Skip logic.")
Значит можно убрать?

2023-06-09 11:03 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogic.kt
> +                if ((variant.lower until variant.upper).contains(hash)) {
Нет. Как это выглядит в коде  
<img width="569" alt="Screenshot 2023-06-09 at 14 03 21" src="https://github.com/mindbox-cloud/android-sdk/assets/13769083/da36eaa8-ec31-49ce-9689-ad7236169d4b">

2023-06-09 11:21 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogic.kt
> +        } ?: setOf()
хочешь провертку на empty вынести в отдельное условие слогом? А то не понимаю в чем проблема

2023-06-09 11:23 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogic.kt
> +                this@InAppABTestLogic.mindboxLogD("Selected inapps $it for ${abtest.id}")
Для всех стандартных логов по умолчанию debug. Когда будет пытаться выгрузить логи, то будем искать не по info а по debug. Так что не понимаю зачем info

2023-06-09 11:25 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
> +                    this@InAppInteractorImpl.mindboxLogD("InApps after abtest logic ${filteredinApps.map { it.id }}")
Не вижу, где это залогировано дважды
<img width="1098" alt="Screenshot 2023-06-09 at 14 24 05" src="https://github.com/mindbox-cloud/android-sdk/assets/13769083/072de92b-1acd-491e-8d9f-b094fdecacab">

2023-06-09 11:26 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/ABTestValidator.kt
> +            mindboxLogW("salt can not be empty")
согласен, попробую перенести в другой PR

2023-06-09 11:27 UTC, enotniy commented on sdk/src/test/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogicTest.kt
> +    fun `abtest logic two variants with inapps1`() = runTest {
у меня есть 2 набора inapp, так же как и в test case есть config1 config2 config3. Как их мне назвать по другому не понятно

2023-06-09 13:19 UTC, dbvasilyev commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogic.kt
> +        } ?: setOf()
Проблема - я как читающий код не понимаю что этот код делает, просто не могу его осознать. Если вынести это в метод с названием которое будет описывать что он делает, скорее это проблема бы не произошла.

2023-06-13 09:09 UTC, dbvasilyev commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogic.kt
> +                this@InAppABTestLogic.mindboxLogD("Selected inapps $it for ${abtest.id}")
Не понимаю что такое стандартные логи. И это не важно. Debug это информация не для клиента, а для разработчика. В релиз продуктах Debug не пишется по умолчанию. Если мы хотим в этом логе уведомить себя или клиента о чем-то, то это Info. В аспекте это записано. Давай тут исправим.

2023-06-13 09:41 UTC, dbvasilyev commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogic.kt
> +                    this@InAppABTestLogic.mindboxLogD("Selected variant $variant for ${abtest.id}")
Договорились что меняем на Info

2023-06-13 09:45 UTC, dbvasilyev commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/abtests/InAppABTestLogic.kt
> +                    this@InAppABTestLogic.mindboxLogD("Selected variant $variant for ${abtest.id}")
Договорились добавить в модель присылаемого АБ-теста айди варианта, и тут и в других местах его использовать для логирования.

2023-06-13 11:10 UTC, dbvasilyev approved these changes

2023-06-13 16:24 UTC, merged