Feature/mbx 2475
mindbox-cloud/android-sdk pull request #375
Opened 2023-06-28 15:58 UTC by Robalim

https://github.com/mindbox-cloud/issues-web-mobile/issues/2475

2023-06-29 10:27 UTC, enotniy requested changes
Не забудь сквошнуть все коммиты, чтобы а то их 58 штук

2023-06-29 10:27 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
> +internal fun View.hideKeyboard(): View? {
Зачем эти изменения?

2023-06-29 10:27 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> -
Вот эти изменения убери из  PR

2023-06-29 10:54 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
> +internal fun View.hideKeyboard(): View? {
Странно, что они изменения, но они после того, как я влил девелоп появились

2023-07-04 12:27 UTC, enotniy requested changes

2023-07-04 12:27 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
> +import android.app.Activity
Все равно вижу эти изменения. Их тут быть не должно

2023-07-05 10:53 UTC, merged