MBX-3064: Add example app
mindbox-cloud/android-sdk pull request #428
Opened 2024-01-24 16:00 UTC by sergeysozinov

https://github.com/mindbox-cloud/issues-web-mobile/issues/3064

2024-01-24 16:40 UTC, Robalim commented on example/app/src/main/java/com/mindbox/example/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
binding в activity нехорошо делать lateinit, тк это потенциальная утечка памяти. Лучше делать его нуллабельным. Если не хочется везде ставить вопросики, то можно писать так:

```
private var _binding: ActivityMainBinding? = null
private val binding: ActivityMainBinding
get() = _binding!!
```
Главное, чтобы в onCreate происходила запись (_binding = ActivityMainBinding.inflate())_, а в onDestroy - обнуление(_binding = null). Обычно я бы еще предложил вынести эту часть в условную BaseMainActivity, чтобы не повторяться, но не знаю, насколько это сложно для example

2024-01-24 16:41 UTC, Robalim commented on example/app/src/main/java/com/mindbox/example/ActivityTransitionByPush.kt
> +        binding = ActivityTrasitionByPushBinding.inflate(layoutInflater)
и тут тоже

2024-01-24 16:45 UTC, Robalim commented on example/app/src/main/java/com/mindbox/example/ExampleApplication.kt
> +        Mindbox.init(
Инициализация же может быть и в activity тоже, может нужен какой-то тоггл, который показывает и пример с активити тоже?

2024-01-25 07:34 UTC, sergeysozinov commented on example/app/src/main/java/com/mindbox/example/ExampleApplication.kt
> +        Mindbox.init(
Вообще не хотелось бы, чтобы кто-то инициализировался в активити. Они постоянно потом косячат и не вызывают initPushService в Application
Хочется в Example максимально надежный вариант продемонстрировать

2024-01-25 09:16 UTC, enotniy requested changes

2024-01-25 09:16 UTC, enotniy commented on example/app/src/main/java/com/mindbox/example/CustomInAppCallback.kt
> +object CustomInAppCallback : InAppCallback {
не будем ссылки давать на описание этих колбеков? Можно прямо на код javadoc в sdk

2024-01-25 09:16 UTC, enotniy commented on example/app/src/main/java/com/mindbox/example/ExampleApplication.kt
> +        Mindbox.init(
Я тоже думаю что не стоит. Очень сильно усложнит пример. И будет похоже на пушок. Когда будут проблемы, то сделаем

2024-01-25 09:16 UTC, enotniy commented on example/app/src/main/java/com/mindbox/example/MindboxHuaweiMessagingService.kt
> +            // If the push notification was not from Mindbox or it contains incorrect data, you can write a fallback to process it.
для Firebase такого коммента не добавил

2024-01-25 09:16 UTC, enotniy commented on example/app/src/main/java/com/mindbox/example/Utils.kt
> +fun chooseInappCallback(selectedInappCallback: RegisterInappCallback) {
Мне не нравится, что это в utils лежит. Потому что в utils обычно лежать очень общие методы, а тут лежат важные методы sdk
Я бы в отдельные файлы это положил и явно их назвал типо MindboxPushMethods, MIndboxInappMethods или как то по другому

2024-01-25 09:16 UTC, enotniy commented on example/app/src/main/res/layout/activity_main.xml
> +
много пробелов

2024-01-25 09:16 UTC, enotniy commented on example/app/src/main/res/layout/activity_main.xml
> +    <TextView
а тут нет пробела между тегами

2024-01-25 09:16 UTC, enotniy commented on example/app/src/main/res/layout/activity_main.xml
> +
не делай переносов внутри тегов

2024-01-25 09:16 UTC, enotniy commented on example/app/src/main/res/layout/activity_main.xml
> +       />
неконсистентно

2024-01-25 09:16 UTC, enotniy commented on example/app/src/main/res/xml/backup_rules.xml
> +<full-backup-content>
что это такое?

2024-01-25 09:16 UTC, enotniy commented on example/app/src/main/res/xml/network_security_config.xml
> +    <base-config>
думаешь надо такое оставлять? Или. это для нас?

2024-01-25 11:31 UTC, sergeysozinov commented on example/app/src/main/res/xml/backup_rules.xml
> +<full-backup-content>
автосгенерировалось - удалил

2024-01-25 11:31 UTC, sergeysozinov commented on example/app/src/main/AndroidManifest.xml
> +        tools:targetApi="31">
если про Rtl - то автоматом добавилось, удалю, в нашем случае ненужно

2024-01-25 11:34 UTC, sergeysozinov commented on example/app/src/main/res/xml/network_security_config.xml
> +    <base-config>
Думаю можно оставить, нам удобно будет при необходимости
Про безопасность: на iOS , к примеру, трафик и так можно посмотреть. 
На Andoid клиент так же у себя может трафик посмотреть

2024-01-25 12:55 UTC, sergeysozinov commented on example/app/src/main/java/com/mindbox/example/CustomInAppCallback.kt
> +object CustomInAppCallback : InAppCallback {
А почему им просто в InAppCallback не провелиться и не посмотреть реализации?

2024-01-25 13:48 UTC, enotniy commented on example/app/src/main/java/com/mindbox/example/CustomInAppCallback.kt
> +object CustomInAppCallback : InAppCallback {
Можно ссылку на javadoc сделать типо @see cloud.mindbox.mobile_sdk.inapp.presentation.InAppCallback

2024-01-29 09:15 UTC, enotniy commented on example/app/src/main/java/com/mindbox/example/ActivityTransitionByPush.kt
> +    private var _binding: ActivityTrasitionByPushBinding? = null
https://developer.android.com/topic/libraries/view-binding#activities

2024-01-29 13:50 UTC, merged