adding user visit count
mindbox-cloud/android-sdk pull request #439
Opened 2024-03-14 18:10 UTC by Robalim

https://github.com/mindbox-cloud/issues-web-mobile/issues/3209

2024-03-14 18:49 UTC, enotniy requested changes

2024-03-14 18:49 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
> +    var userVisitCount: Int
Перенос строки забыл

2024-03-14 18:49 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                val userVisitCount = MindboxPreferences.userVisitCount
Я бы вынес в отдельный обьет всю логику visit. Инкремент, выбор дефотного и так далее. А то у тебя логика размазана по разным местам

2024-03-14 18:49 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                mindboxLogI("New user visit count after increment is ${MindboxPreferences.userVisitCount}")
Давай просто в одном логе напишем, что было столько стало столько

2024-03-14 18:49 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                val userVisitCount = MindboxPreferences.userVisitCount
А при повторной инициализации в одной сессии не будет инкремента?

2024-03-14 19:50 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                val userVisitCount = MindboxPreferences.userVisitCount
Ты хочешь в 2 местах работать с преференсами? А это ок?

2024-03-14 19:53 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
> +    var userVisitCount: Int
Добавил

2024-03-14 19:53 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                mindboxLogI("New user visit count after increment is ${MindboxPreferences.userVisitCount}")
Сделал один лог

2024-03-15 07:46 UTC, enotniy commented
Название RP без номер тикета

2024-03-15 07:52 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            else
мы никогда не пишем
```
}
else
{
```
только 
`} else {`

2024-03-15 07:52 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/UserVisitManagerImpl.kt
> +    override fun saveUserVisit() {
тут бы тест хорошо смотрелся

2024-03-15 09:37 UTC, enotniy approved these changes

2024-03-15 12:32 UTC, sergeysozinov approved these changes

2024-03-15 12:39 UTC, merged