Feature/mbx 3181
mindbox-cloud/android-sdk pull request #440
Opened 2024-03-15 11:06 UTC by sergeysozinov

https://github.com/mindbox-cloud/issues-web-mobile/issues/3181

2024-03-18 08:43 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
> +
Кажется, что эти расширения тут ни к месту, я бы их оставил в месте проверке. Или может сделать отдельный класс, который этим будет заниматься. Иначе Extensions в какую-то свалку превращается

2024-03-18 08:43 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
А здесь с какой целью изменение?

2024-03-18 08:46 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
> +                mindboxLogI("InApps after filtered by push permission status for show $filteredInAppsByNotificationStatus")
Мне не очень нравятся названия переменных, они заставляют погружаться в контекст. Надо подумать как их переименовать

2024-03-18 08:50 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManager.kt
> +    fun requestPermission(activity: Activity)
Это очень странный контракт. 
Во-первых, если ты хочешь сделать метод вызова коллбэка, то синтаксически правильнее будет делать просто object.callback(), а не callCallback()
Во-вторых, метод для коллбэка который ты используешь работает с коллбэком, который существует только в реализации, так лучше не делать.

В-третьих, не очень понятно, зачем он вообще нужен, почему просто не сделать метод, открывающий настройки

2024-03-18 08:51 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/InAppAction.kt
> +    private fun isNeedDismiss(): Boolean {
Обычно когда тебе нужен метод, завязанный на "Если", принято писать не isNeed, а should

2024-03-18 08:52 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    override fun show(currentRoot: ViewGroup,currentActivity: Activity) {
С какой целью тут везде появилась activity?

2024-03-18 08:54 UTC, Robalim commented on sdk/src/test/java/cloud/mindbox/mobile_sdk/models/InAppStub.kt
> +            Layer.ImageLayer.Source.UrlSource(url = "https:/mindbox.com")
в стабах не должно быть непрозрачных значений по умолчанию, потому что неочевидно, с чем тест работает. Если тебе нужно значение, ты берешь стаб и делаешь Stub.copy заполняя нужные тебе поля. Вся идея с ними нужна только для того, чтобы при изменении конструктора не пришлось править кучу тестов.

2024-03-18 08:56 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
Чтобы при ответе на реквест на бэк сразу отправлялся обновленный статус.
В кейсе с клиентскими запросами пермиссии - им не обязательно будет вызывать updateNotificationPermission

2024-03-18 08:57 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
> +                mindboxLogI("InApps after filtered by push permission status for show $filteredInAppsByNotificationStatus")
Например? Мне наоборот кажется, что читаемо и без контекста можно понять

2024-03-18 08:57 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManager.kt
> +    fun requestPermission(activity: Activity)
Ага, тут надо переделать, самому не нравится

2024-03-18 09:02 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppFilteringManagerImpl.kt
> +    private val mindboxNotificationManager: MindboxNotificationManager
Мне не очень нравится, что сущность которая лежит в presеntation слое инджектится в доменный, мы создаем зависимость, которой не должно быть. И я не до конца понимаю, относится ли в реальности эта сущность к presentation слою. По ощущениям нужна еще одна сущность, которая должна выяснять есть ли разрешение и к которой нужно обращаться из менеджера.  @enotniy Помоги тут, как лучше

2024-03-18 09:02 UTC, Robalim requested changes
Ничего не понятно, но очень интересно

2024-03-18 09:10 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
мы не можем в кейсе , когда shouldPermissionReteonale==true узнать результат запроса

2024-03-18 09:12 UTC, enotniy requested changes

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                    openNotificationSettings(activity)
не понимаю смысла этого колбека. это всегда открытие настроек. Так почему просто не  метод открыть настрйоки использовать?

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/PushActivationActivity.kt
> +                mindboxLogI("User rejected permission two time, try open settings")
два или больше

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/PushActivationActivity.kt
> +            finish()
а в onCreate нельзя finish вызвать?

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    protected open fun addUrlSource(layer: Layer.ImageLayer, inAppCallback: InAppCallback,activity:Activity) {
пробела не хватает

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +                redirectUrl=result.redirectUrl
форматирование

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/InAppActionHandler.kt
> +    fun handleAction(
если класс InAppActionHandler, то метод можно просто handle назвать

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +            InAppActionHandler.handleAction(layer.action.createAction(mindboxNotificationManager),activity){ result->
Ради этого сюда активити тащить не надо.
Ты в метод передал и layer и Activity. Чтобы вызвать handle, тебе нужно layer и activity, так не проще тогда сюда уже передать нужный handler?

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    override fun show(currentRoot: ViewGroup,currentActivity: Activity) {
форматирование

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppImageView.kt
> +@SuppressLint("AppCompatCustomView")
а это почему так?

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/ModalWindowInAppViewHolder.kt
> +                        addUrlSource(layer, inAppCallback,currentActivity)
почему тут отступ появился?

2024-03-18 09:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/SnackbarInAppViewHolder.kt
> + import android.app.Activity
а тут пробел какой-то

2024-03-18 09:12 UTC, enotniy commented on sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/managers/MobileConfigSerializationManagerTest.kt
> +                                    top = 0.03
зачем ты тут выставляешь значения? Для работы теста это лишнее

2024-03-18 09:12 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
> +                mindboxLogI("InApps after filtered by push permission status for show $filteredInAppsByNotificationStatus")
Может изменить сигнатуру слегка и вынести эти списки в отдельный filter в цепочке. Или как-то обобщить хотя бы логику в названиях. Чтобы не в одном случае filteredInApps а в другом filteredBy что-то

2024-03-18 09:25 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    override fun show(currentRoot: ViewGroup,currentActivity: Activity) {
activity нужна в методе `addUrlSource` , решил прокинуть тут, вместе с currentRoot

2024-03-18 09:27 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    override fun show(currentRoot: ViewGroup,currentActivity: Activity) {
root берется из currentRoot, а из currentRoot можно через getContext получить активити

2024-03-18 09:30 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppFilteringManagerImpl.kt
> +    private val mindboxNotificationManager: MindboxNotificationManager
это же все ради одного метода isNotificationEnabled?

2024-03-18 10:42 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppFilteringManagerImpl.kt
> +    private val mindboxNotificationManager: MindboxNotificationManager
да

2024-03-18 10:47 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManager.kt
> +    fun callCallback()
ты про callCallback? тут переделаю, да

2024-03-18 10:50 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/PushActivationActivity.kt
> +                mindboxLogI("User rejected permission two time, try open settings")
но отклонить он может только 2 раза, потом пользователь не отклоняет
Давай поменяю на `already rejected permission two time`

2024-03-18 10:56 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppImageView.kt
> +@SuppressLint("AppCompatCustomView")
Lint не давай использовать ImageView после подключения appCompat
```
Lint found 1 errors, 4 warnings. First failure:

Error: /home/runner/work/android-sdk/android-sdk/sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppImageView.kt:13: Error: This custom view should extend androidx.appcompat.widget.AppCompatImageView instead [AppCompatCustomView]
```

2024-03-18 11:14 UTC, sergeysozinov commented on sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/managers/MobileConfigSerializationManagerTest.kt
> +                                    top = 0.03
Красиво выглядело, много памяти не съедало. 
Для теста да , лишнее, исправил

2024-03-18 12:09 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                    openNotificationSettings(activity)
Да, смысла особого не оказалось
Не хотел ссылку на активити тащить во временную активити, но потестил, запуск окна настроек со временной активити ничего не ломает

2024-03-18 12:09 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManager.kt
> +    fun requestPermission(activity: Activity)
Передалал

2024-03-18 12:17 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        putExtra("app_package", activity.packageName)
А что конкретно предлагаешь вынести в константы?
android.settings.APP_NOTIFICATION_SETTINGS? Вместо трех слов станет 2, а читаемости не добавит, кмк

2024-03-18 12:33 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
> +
но тогда в интерфейс выносить придется, чтобы можно было тестировать нормально, такое ок?

2024-03-18 13:04 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
> +
сделал приватным hasInAppImageLayerWithRedirectUrlAction, тестировать будем через метод `filterPushInAppsByPermissionStatus`

2024-03-18 13:14 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/PushActivationActivity.kt
> +            finish()
Если дергать метод с открытием настроек из этой активити - точно нет, она закроется до выполнения колбэка
Если использовать какой-то прокси метод или колбэк для открытия настроек - в теории можно
А почему тебе не нравится вызывать его после обработки колбэка?

2024-03-18 13:23 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +            InAppActionHandler.handleAction(layer.action.createAction(mindboxNotificationManager),activity){ result->
вот тут не понял

2024-03-18 13:38 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
> +                mindboxLogI("InApps after filtered by push permission status for show $filteredInAppsByNotificationStatus")
```
val filteredInApps =
                    inAppFilteringManager.filterUnShownInAppsByEvent(inApps, event).let {
                        inAppFilteringManager.filterPushInAppsByPermissionStatus(it)
                    }.also { inAppsFilteredAfterCheckPermissionStatus ->
                        mindboxLogI("InApps after filtered by push permission status $inAppsFilteredAfterCheckPermissionStatus")
                    }
                mindboxLogD("Event: ${event.name} combined with $filteredInApps")
```
Как тебе вот такое решение?

2024-03-18 13:46 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
> +                mindboxLogI("InApps after filtered by push permission status for show $filteredInAppsByNotificationStatus")
Даже бы лог mindboxLogI("InApps after filtered by push permission status $inAppsFilteredAfterCheckPermissionStatus")
Поменял на ""InApps was filtered by push permission status"

2024-03-18 13:54 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
> +                mindboxLogI("InApps after filtered by push permission status for show $filteredInAppsByNotificationStatus")
Лог можно не трогать, хотя mindboxLogD можно заменить попутно на mindboxLogI, а в целом мне все равно не нравится. Let сбивает с толку, как будто там может быть null. Если уж так делать, то можно написать extension для листа внутри filteringManager, который делает то же самое, но вызывается от листа и сделать типа inapps.filterUnshowninappsbyevent.filterpushinappsbypermission

2024-03-18 13:56 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    override fun show(currentRoot: ViewGroup,currentActivity: Activity) {
Или может создать свойство` currentActivity` в` MindboxNotificationManager` и обновлять в его в `onResume`?
Тогда не придется ничего тащить

2024-03-18 13:57 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
Почему? Он туда же прилетит же

2024-03-18 13:59 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        arrayOf(Constants.POST_NOTIFICATION),
вот эта константа не нужна отдельно. Она уже есть Manifest.permission.POST_NOTIFICATION

2024-03-18 14:00 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        arrayOf(Constants.POST_NOTIFICATION),
а зачем мы по разному запрашиваем пермишоны? почему не сделать startActivity дважды?

2024-03-18 14:04 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
куда туда? 
Если оставить как есть, то обновление разрешения улетит на бэк только после того, как апку свернут и развернут
Так как , в случае, когда мы нажимаем "Allow" или "Not Allow" сработает метод onResume

2024-03-18 14:08 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        arrayOf(Constants.POST_NOTIFICATION),
Про константу, Егор просил вынести. Возможно я его не так понял, мне тоже кажется, что не нужно этого делать. 

Про запрос:  это самый простой способ сделать повторный запрос, после первого отклонения
Мы не можем его сделать в permissionLauncher так как  у нас в двух случаях может срабатывать колбэк (!isGranted и shouldRationalePermission==true) 
1) Пользователь реально отклонил второй раз
2) Мы не смогли показать окно, так как было 2 отказа и должны показать настройки
Этот запрос сделан отдельно, чтобы гарантировать, что у нас кейс, когда нужно открыть настройки

2024-03-18 14:11 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
> +                mindboxLogI("InApps after filtered by push permission status for show $filteredInAppsByNotificationStatus")
Лог можно изменить, у тебя инаппы в них продублируются, зачем дублировать? Важно просто инфу вывести, что фильтровали

2024-03-18 14:12 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    override fun show(currentRoot: ViewGroup,currentActivity: Activity) {
https://github.com/android/android-ktx/issues/363

2024-03-18 14:13 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    override fun show(currentRoot: ViewGroup,currentActivity: Activity) {
https://stackoverflow.com/questions/8276634/how-to-get-hosting-activity-from-a-view или вот

2024-03-18 14:13 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    override fun show(currentRoot: ViewGroup,currentActivity: Activity) {
но прежде чем это делать посмотри в коммент про запрос разрешения и почему они разные

2024-03-18 14:14 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
> мы не можем в кейсе, когда shouldPermissionReteonale==true узнать результат запроса

ничего не понял. Если shouldPermissionReteonale == true, то мы покажем окно и реультат узнаем в launcher, оттуда вызовем обновление

2024-03-18 14:14 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppFilteringManagerImpl.kt
> +    private val mindboxNotificationManager: MindboxNotificationManager
тогда давай его вынесем из manager и все. Сделать его утилитным от context. Тогда контекст в мененджер не придется тащить

2024-03-18 14:14 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        putExtra("app_package", activity.packageName)
все строки надо унести в константы, чтобы было понятно, что это нужные слова, а не просто какие-то рандомные строки

2024-03-18 14:14 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/PushActivationActivity.kt
> +                mindboxLogI("User rejected permission two time, try open settings")
ну ладно, так то да

2024-03-18 14:14 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/PushActivationActivity.kt
> +            finish()
просто боюсь, что эта прозрачная активити может каким-то образом остаться на экране. Например пользователь назад нажмет и окно закроется, а активити останется. Она должна гарантировано уничтожаться

2024-03-18 14:19 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
Если shouldPermissionReteonale == true, то мы понимаем, что первый раз был отказ и  вызываем requestPermission
![image](https://github.com/mindbox-cloud/android-sdk/assets/103035673/9d426c93-b588-4c9d-b126-d0acd887369c)

2024-03-18 14:23 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        arrayOf(Constants.POST_NOTIFICATION),
если пользователь отклонил второй раз, то shouldShowPermissionRationale будет false

2024-03-18 14:23 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        arrayOf(Constants.POST_NOTIFICATION),
@enotniy А чем тебе не нравится Manifest.permission.POST_NOTIFICATIONS?

2024-03-18 14:29 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        putExtra("app_package", activity.packageName)
и еще "android.settings.APP_NOTIFICATION_SETTINGS" и Settings.ACTION_APP_NOTIFICATION_SETTINGS полностью совпадают, почему вверху одно, а тут другое?

2024-03-18 14:32 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        arrayOf(Constants.POST_NOTIFICATION),
>если пользователь отклонил второй раз, то shouldShowPermissionRationale будет false
Да тут опечатался, речь про shouldRationalePermission==false

2024-03-18 14:35 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
можем, но при втором отказе, мы так же попадаем в колбэк, где !isGranted и !shouldPermissionRationale.
Текущая логика нам позволяет открывать настройки, когда мы понимаем, что было 2 отказа, в твоем кейсе она сломается

2024-03-18 14:36 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    override fun show(currentRoot: ViewGroup,currentActivity: Activity) {
А  мои 2 предложения почему не нравятся?

2024-03-18 14:37 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        arrayOf(Constants.POST_NOTIFICATION),
А какая нам разница между отклонил второй раз и уже было 2 отказа?

2024-03-18 14:38 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        arrayOf(Constants.POST_NOTIFICATION),
когда было 2 отказа - надо открывать настройки
когда отклонил 2ой раз - ничего делать не хотим

2024-03-18 14:48 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    override fun show(currentRoot: ViewGroup,currentActivity: Activity) {
Прокидывать activity нехорошо, потому что она не нужна в большинстве мест, у тебя связность повышается без причины. А следить за активити в мэнэджере плохо, потому что мы уже следим за активити во вью дисплеере и следить в 2 местах не хорошо

2024-03-18 15:02 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
Если у тебя в коллбэке !isGranted и !shouldPermissionRationale, то ты точно знаешь, что надо открывать настройки

2024-03-18 15:03 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
Тебе разве что нужно запомнить, что если ты уже проверял shouldShowPermissionRationale и оно уже было true, то в таком случае не открывать

2024-03-18 16:16 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                            mindboxScope.launch {
Обсудили
Уберем вызов requestPermission, добавим флаг, чтобы понимать, что настройки не надо открывать. Тогда это изменение можно откатить

2024-03-18 16:37 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
> +                        arrayOf(Constants.POST_NOTIFICATION),
Тут обсудили, сделали запрос через permissionLaucher

2024-03-19 13:27 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DataModule.kt
> +    override val permissionManager: PermissionManager by lazy { PermissionManagerImpl(appContext) }
InAppFilteringManager не хранится в памяти непрерывно, зачем permissionManager lazy?

2024-03-19 13:59 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DataModule.kt
> +    override val permissionManager: PermissionManager by lazy { PermissionManagerImpl(appContext) }
Не заметил, что InAppFiltering не хранится в памяти непрерывно, да, тогда использовать lazy неэффективно

2024-03-21 08:19 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/InAppActionHandler.kt
> +    fun createAction(
А для чего этот метод публичный? Такое ощущение, что его можно сделать приватным прям в этом классе, в handle передавать action и писать when. Как будто в отрыве от handle createAction не нужен

2024-03-21 08:20 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
> +    private const val KEY_REQUEST_PERMISSION_COUNT = "key_request_permission_count"
везде выше капс, а тут не капс

2024-03-21 08:21 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +    protected open fun addUrlSource(
проверяй в будущем, чтобы вот таких изменений не было, это потом ни в Ide читать, ни смотреть не удобно

2024-03-21 08:23 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
> +    private const val KEY_REQUEST_PERMISSION_COUNT = "key_request_permission_count"
В целом, там где-то капс, где-то не капс
Сам я ориентировался на твой последний коммит
https://github.com/mindbox-cloud/android-sdk/blob/develop/sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt#L30

2024-03-21 08:26 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
> +    private const val KEY_REQUEST_PERMISSION_COUNT = "key_request_permission_count"
Да, ты прав, в гитхабе просто не заметно. Оставь тогда так, в баглоге можно это поправить

2024-03-21 08:38 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/InAppActionHandler.kt
> +    fun createAction(
а зачем when? почему просто вот так не сделать? а так, да, можно и сделать его публичным
![image](https://github.com/mindbox-cloud/android-sdk/assets/103035673/059357fb-e111-45a5-b1f3-39cd5406cfc4)

2024-03-21 10:29 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/InAppActionHandler.kt
> +    fun createAction(
Ну, кстати, тут тогда много переделывать надо, если отвязываться от ImageLayer, потому что мы получаем в AddSourceUrl уже layer.image
![image](https://github.com/mindbox-cloud/android-sdk/assets/103035673/62afb294-588a-4bf4-80a6-2e0885d31ed1)
И там дальше тянется до метода show. Предлагаю не в рамках этой задачи.
Оставлю как сейчас скрином выше предложил

2024-03-21 13:32 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/RequestPermissionManagerImpl.kt
> +    override fun getCounterValue(): Int = MindboxPreferences.requestPermissionCount
тут лучше, чтобы поддержать схему именования просто сделать getCounter или getRequestCounter. value наводит на мысль на какой-то декоратор, а его там нет

2024-03-21 13:33 UTC, Robalim commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppImageView.kt
> +@SuppressLint("AppCompatCustomView")
А если у нас теперь обычная activity, то там нужна еще зависимость appCompat?

2024-03-21 13:33 UTC, Robalim approved these changes
В остальном вроде ок

2024-03-21 15:03 UTC, enotniy approved these changes

2024-03-21 15:03 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/PushActivationActivity.kt
> +                        requestPermissionManager.decreaseRequestCounter()
Тут случай dismiss? Добавь лог тогда

2024-03-21 15:03 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/PushActivationActivity.kt
> +        if (event.action == MotionEvent.ACTION_DOWN) {
Это работает?

2024-03-21 15:03 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
> +        inAppActionHandler.mindboxView=currentRoot
Пробелы забыл

2024-03-21 15:46 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppImageView.kt
> +@SuppressLint("AppCompatCustomView")
Надо выпилить, я ее даже выпиливал, а потом ревертнул, так как подумал, что без нее активити получить не можем

2024-03-21 15:50 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/actions/PushActivationActivity.kt
> +        if (event.action == MotionEvent.ACTION_DOWN) {
Да, при клике на активити, она закроется

2024-03-22 08:06 UTC, merged