MBX-3508: change image scale type
mindbox-cloud/android-sdk pull request #478
Opened 2024-07-12 14:44 UTC by sergeysozinov

2024-07-15 06:57 UTC, enotniy requested changes

2024-07-15 06:57 UTC, enotniy commented on sdk/src/main/res/layout/notification_custom_text_with_image.xml
> +        android:id="@+id/text_view_title"
id этих view совпадают с теми, что в дефотных пушах? Ты проверял?

2024-07-15 06:57 UTC, enotniy commented on sdk/src/main/res/values/dimens.xml
> +    <dimen name="notification_content_margin_end">16dp</dimen>
давай все наши ресурсы начинать с mindbox

2024-07-15 07:04 UTC, sergeysozinov commented on sdk/src/main/res/layout/notification_custom_text_with_image.xml
> +        android:id="@+id/text_view_title"
почему они должны совпадать? мы ничего не знаем о layout'ах в дефолтных пушах

2024-07-15 08:09 UTC, enotniy commented on sdk/src/main/res/layout/notification_custom_text_with_image.xml
> +        android:id="@+id/text_view_title"
ну да, в дефолте вообще называется title, message, icon. Путь будет как будет

2024-07-15 08:12 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                setStyle(NotificationCompat.DecoratedCustomViewStyle())
кастомный стиль не влияет на setColor?

2024-07-15 08:52 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                context =context,
пробел потерял

2024-07-15 08:52 UTC, enotniy commented on sdk/src/main/res/layout/notification_custom_text.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
проверял как на RLT будет выглядеть?

2024-07-15 09:28 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                setStyle(NotificationCompat.DecoratedCustomViewStyle())
Смена цвета иконки работает, проверял

2024-07-15 09:28 UTC, sergeysozinov commented on sdk/src/main/res/layout/notification_custom_text.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Не проверял, посмотрю

2024-07-25 07:26 UTC, enotniy commented
Закрываю, потому что делаем другое решение

2024-07-25 07:26 UTC, closed without merging