MBX-2936: added temporary migration
mindbox-cloud/android-sdk pull request #488
Opened 2024-08-20 07:50 UTC by sergeysozinov

https://github.com/mindbox-cloud/issues-web-mobile/issues/2936

2024-08-20 08:05 UTC, enotniy requested changes

2024-08-20 08:05 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +        sendWithoutChanges: Boolean = false
обычно называют force, такой параметр

2024-08-20 08:05 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            if (isUpdateInfoRequired(isTokenAvailable, pushToken, isNotificationEnabled, sendWithoutChanges)) {
зачем прокидывать внутрь isUpdateInfoRequired ?
почему бы просто не написать 

`if (sendWithoutChanges || isUpdateInfoRequired(...))`

2024-08-20 08:05 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
> +                MindboxPreferences.isDeviceInfoNeedUpdated = false
проверку версий не будешь делать?

2024-08-20 08:05 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
> +                MindboxPreferences.isDeviceInfoNeedUpdated = false
надо еще вот что проверить, как это будет работать, когда этого кода не будет в следующей версии

2024-08-20 08:09 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
> +                MindboxPreferences.isDeviceInfoNeedUpdated = false
Проверку версий не планирую делать, чтобы потом не заафектило на следующие миграции. 
Если поднять версии, то в следующих миграциях придется это учитывать. А в текущей миграции, просто останется доп запись в преференсах, которая ни на что не влияет

2024-08-20 08:14 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            if (isUpdateInfoRequired(isTokenAvailable, pushToken, isNotificationEnabled, sendWithoutChanges)) {
Да, так будет лучше, согласен

2024-08-20 08:49 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
> +                MindboxPreferences.isDeviceInfoNeedUpdated = false
а как тебе вариант просто затирать какие-то значения в preferences, тогда infoupdate сам отправится? По текущей механике, без всяких форсов

2024-08-20 09:00 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
> +                MindboxPreferences.isDeviceInfoNeedUpdated = false
На мой взгляд, форс лучше тем, что мы точно ничего не сломаем. В преференсах придется чистить или токен или разрешение на пуши.
В случае, если мы потрем токен, то сработает `registerToken`, если к примеру FCM моргнет, то мы токен не получим, отправим пустой токен. На какой-то период можем потерять возможность коммуникации с клиентом

Можно затирать `MindboxPreferences.isNotificationEnabled`, но по умолчанию при его остутствии в префах вернется true. Т.е. для тех у кого разрешение есть - не сработает отправка. 
Если не затирать, а изменять на false не сработает отправка у тех, у кого они отключены

2024-08-20 09:04 UTC, enotniy commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
> +                MindboxPreferences.isDeviceInfoNeedUpdated = false
страшно, что может force забаговать как-то и мы заспамим сервер пустыми апдейтами. Давай завернем в try catch и будем надежно флаг поднимать, даже если все сломалось

2024-08-20 09:04 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
> +                MindboxPreferences.isDeviceInfoNeedUpdated = false
Справедливости ради, `val token = getToken(context)` , сейчас сработает каждый раз при открытии приложения

2024-08-20 09:11 UTC, sergeysozinov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
> +                MindboxPreferences.isDeviceInfoNeedUpdated = false
Ты имеешь в виду вот так?
```
Mindbox.mindboxScope.launch {
                try {
                    Mindbox.updateAppInfo(context, forceChanges = true)
                } catch (e: Exception) {
                   mindboxLogE("Error in migration version2101MBX2936")
                } finally {
                    MindboxPreferences.isDeviceInfoNeedUpdated = false
                }
            }
```

2024-08-21 07:01 UTC, enotniy approved these changes

2024-09-16 07:00 UTC, closed without merging